import type { NextPage } from "next";
import Head from "next/head";
import Carousel from "../components/home/Carousel";
import Hero from "../components/home/Hero";
import Inspiration from "../components/home/Inspiration";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>CookiBooki</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Carousel />
        <Inspiration />
      </main>
    </>
  );
};

export default Home;
